---
- hosts: db
  gather_facts: false
  vars:
    myvar: "Hello world"
  tasks:
    - name: define variable
      debug: msg="{{ myvar | default(" Foo Bar")  }}"
    - name: undefine variable
      debug: msg="{{ undefined_var | default("Foo Bar") }}"
    - name: default with secound parameter
      debug: msg="{{ lookup('env','HOME') | default('/home/default',true) }}"
    - name: without default
      debug: msg="{{ lookup('env','I_HOME')  }}"
    - name: default with single parameter
      debug: msg="{{ lookup('env','I_HOME')| default('/home/defualt') }}"
    - name: default with secound parameter
      debug: msg="{{ lookup('env','I_HOME')| default('/home/defualt',true) }}"
