---
- name: install web server to serverx
  hosts: db
  remote_user: mild
  tasks:
   - name: Install httpd
     yum:
       name: httpd
       state: present
     become: true 
   - name: Enable service httpd
     service:
       name: httpd
       enabled: yes
     become: true
   - name: Start http
     service:
       name: httpd
       state: started
   - name: Open Firewall
     firewalld:
       service: http
       permanent: true
       state: enabled
       
